### ISSUE TITLE
Create performance table & graphs

### ISSUE THREAD

**Issue by kloppstock** [kloppstock/squared_matrix_multiplication#12]
Create 1 table for all parformance measurements. Display these results in 1 or 2 graphs.
Store these files in the [Docs](https://github.com/kloppstock/squared_matrix_multiplication/tree/master/docs).

**Comment by de-narm** [comment]
benchmark tables added

**Comment by arbu** [comment]
@De-Narm wär cool, wenn du die CSVs für C und Fortran noch höchlädst

**Comment by de-narm** [comment]
Entschuldige, ich war gestern etwas arg übermüdet. Jetzt sind die richtigen Dateien alle hochgeladen!

**Comment by arbu** [comment]
gibt es noch Vorschläge für die Graphen?

**Comment by de-narm** [comment]
Ich würde noch eine Notiz einfügen, dass alle Sprache, auße Java, immer multithreaded sind um den Vergleichsgraphen in den richtigen Kontext zu setzten.

**Comment by arbu** [comment]
Fortran war auch nicht multithreaded und bei Haskell würde ich behaupten, dass es für den Vergleich ziemlich irrelevant ist. Ich würde einfach an die C-Version noch (OpenMP) anhängen

**Comment by kloppstock** [comment]
Ich kümmere mich morgen noch um die Docu und schreibe das alles mit rein.
