### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by kloppstock** [kloppstock/squared_matrix_multiplication#14]
Does anyone know why the maximal achived performance is only 6.44% of the FPPP?
(see [performance.csv](https://github.com/kloppstock/squared_matrix_multiplication/blob/master/benchmarks/performance.csv))

**Comment by de-narm** [comment]
6.44% is astonishingly low since pretty much nothing else was running. Since three out of four languages achieved roughly the same performance, it can't be our code either I'd assume. The weak link seems to be the FPPP itself, even though we even asked about it.

**Comment by kloppstock** [comment]
According to [Wikipedia](https://en.wikipedia.org/wiki/FLOPS#Computing) our calculation should be right. I guess this issue will never be fixed. I already sent the current version to our supervisor.
